"""Builds ZigDash's bundled fonts (docs/design/signal-2.0.md §2–3).

Fetches the sources into build/fonts-src/ (cached), then writes subsets to
assets/fonts/:
  SpaceGrotesk-Medium/Bold      Latin, from the variable font at wght 500/700
  IBMPlexSans-Regular/SemiBold  Latin, from the variable font at wdth 100, wght 400/600
  IBMPlexSansHebrew-Regular/SemiBold  the Hebrew block only (Latin comes from Plex Sans)
  MaterialSymbolsRounded-subset the glyphs in tool/fonts/symbols.txt, GRAD 0,
                                opsz 24, wght 400, FILL kept as a variable axis
and copies their licences to assets/fonts/licenses/.

Needs fonttools (and brotli). Without a venv:
  pip install --target build/pylib fonttools brotli
  PYTHONPATH=build/pylib python3 tool/fonts/build_fonts.py
"""
import os
import shutil
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'build', 'fonts-src')
OUT = os.path.join(ROOT, 'assets', 'fonts')
RAW = 'https://raw.githubusercontent.com/'
SOURCES = {
    'SpaceGrotesk.ttf': 'google/fonts/main/ofl/spacegrotesk/SpaceGrotesk%5Bwght%5D.ttf',
    'SpaceGrotesk-OFL.txt': 'google/fonts/main/ofl/spacegrotesk/OFL.txt',
    'IBMPlexSans.ttf': 'google/fonts/main/ofl/ibmplexsans/IBMPlexSans%5Bwdth,wght%5D.ttf',
    'IBMPlexSans-OFL.txt': 'google/fonts/main/ofl/ibmplexsans/OFL.txt',
    'IBMPlexSansHebrew-Regular.ttf': 'google/fonts/main/ofl/ibmplexsanshebrew/IBMPlexSansHebrew-Regular.ttf',
    'IBMPlexSansHebrew-SemiBold.ttf': 'google/fonts/main/ofl/ibmplexsanshebrew/IBMPlexSansHebrew-SemiBold.ttf',
    'IBMPlexSansHebrew-OFL.txt': 'google/fonts/main/ofl/ibmplexsanshebrew/OFL.txt',
    'MaterialSymbolsRounded.ttf': 'google/material-design-icons/master/variablefont/MaterialSymbolsRounded%5BFILL,GRAD,opsz,wght%5D.ttf',
    'MaterialSymbolsRounded.codepoints': 'google/material-design-icons/master/variablefont/MaterialSymbolsRounded%5BFILL,GRAD,opsz,wght%5D.codepoints',
    'MaterialSymbols-LICENSE.txt': 'google/material-design-icons/master/LICENSE',
}

# Latin, Latin-1 Supplement, Latin Extended-A, General Punctuation, the
# units and signs tiles show, and the bidi isolates ZigDash wraps numbers in.
LATIN = ('U+0020-007E,U+00A0-00FF,U+0100-017F,U+2000-206F,U+20AC,U+2122,'
         'U+2190-2193,U+2212,U+00B0,U+00B5,U+00B3,U+2066-2069')
HEBREW = 'U+0590-05FF,U+FB1D-FB4F,U+2000-206F,U+20AA'


def fetch():
    os.makedirs(SRC, exist_ok=True)
    for name, path in SOURCES.items():
        dest = os.path.join(SRC, name)
        if not os.path.exists(dest):
            urllib.request.urlretrieve(RAW + path, dest)


def cut(font, unicodes, out, keep_features=True):
    opts = subset.Options()
    opts.layout_features = ['*'] if keep_features else []
    opts.name_IDs = ['*']
    opts.notdef_outline = True
    opts.glyph_names = False
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=subset.parse_unicodes(unicodes))
    sub.subset(font)
    font.save(os.path.join(OUT, out))


def static(src, out, unicodes, **axes):
    font = instancer.instantiateVariableFont(TTFont(os.path.join(SRC, src)), axes)
    cut(font, unicodes, out)


def symbols():
    names = [l.strip() for l in open(os.path.join(ROOT, 'tool', 'fonts', 'symbols.txt'))
             if l.strip() and not l.startswith('#')]
    points = {}
    for line in open(os.path.join(SRC, 'MaterialSymbolsRounded.codepoints')):
        name, hexcode = line.split()
        points[name] = int(hexcode, 16)
    missing = [n for n in names if n not in points]
    if missing:
        raise SystemExit(f'not in Material Symbols Rounded: {missing}')
    # Subset the full variable font first (the instancer trips over it
    # whole), then pin every axis but FILL.
    font = TTFont(os.path.join(SRC, 'MaterialSymbolsRounded.ttf'), lazy=False)
    opts = subset.Options()
    opts.layout_features = []  # code points only; no ligature lookups
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=sorted({points[n] for n in names}))
    sub.subset(font)
    font = instancer.instantiateVariableFont(font, {'GRAD': 0, 'opsz': 24, 'wght': 400})
    font.save(os.path.join(OUT, 'MaterialSymbolsRounded-subset.ttf'))
    # The Dart side reads code points from this generated table.
    with open(os.path.join(ROOT, 'lib', 'core', 'theme', 'symbols.g.dart'), 'w') as f:
        f.write('// GENERATED by tool/fonts/build_fonts.py from tool/fonts/symbols.txt.\n')
        f.write('// Do not edit by hand.\n\n')
        f.write("import 'package:flutter/widgets.dart';\n\n")
        f.write('/// App icons from the bundled Material Symbols Rounded subset (ADR 0005).\n')
        f.write('/// Draw with [SignalIcon] to get the filled-when-active cue.\n')
        f.write('abstract final class Symbols {\n')
        for n in names:
            parts = n.split('_')
            ident = parts[0] + ''.join(x.capitalize() for x in parts[1:])
            if ident[0].isdigit():
                ident = f's{ident}'
            f.write(f"  static const {ident} = IconData(0x{points[n]:x}, fontFamily: 'MaterialSymbolsRounded');\n")
        f.write('}\n')


def main():
    fetch()
    os.makedirs(os.path.join(OUT, 'licenses'), exist_ok=True)
    static('SpaceGrotesk.ttf', 'SpaceGrotesk-Medium.ttf', LATIN, wght=500)
    static('SpaceGrotesk.ttf', 'SpaceGrotesk-Bold.ttf', LATIN, wght=700)
    static('IBMPlexSans.ttf', 'IBMPlexSans-Regular.ttf', LATIN, wdth=100, wght=400)
    static('IBMPlexSans.ttf', 'IBMPlexSans-SemiBold.ttf', LATIN, wdth=100, wght=600)
    for w in ('Regular', 'SemiBold'):
        cut(TTFont(os.path.join(SRC, f'IBMPlexSansHebrew-{w}.ttf')), HEBREW,
            f'IBMPlexSansHebrew-{w}.ttf')
    symbols()
    for lic, name in [('SpaceGrotesk-OFL.txt', 'SpaceGrotesk-OFL.txt'),
                      ('IBMPlexSans-OFL.txt', 'IBMPlexSans-OFL.txt'),
                      ('IBMPlexSansHebrew-OFL.txt', 'IBMPlexSansHebrew-OFL.txt'),
                      ('MaterialSymbols-LICENSE.txt', 'MaterialSymbols-LICENSE.txt')]:
        shutil.copy(os.path.join(SRC, lic), os.path.join(OUT, 'licenses', name))
    total = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT) if f.endswith('.ttf'))
    for f in sorted(os.listdir(OUT)):
        if f.endswith('.ttf'):
            print(f'{f:40s} {os.path.getsize(os.path.join(OUT, f)) / 1024:7.1f} KB')
    print(f'{"total":40s} {total / 1024:7.1f} KB')


if __name__ == '__main__':
    main()
