"""Generates lib/core/utils/material_icon_rounded.g.dart (ADR 0005).

Maps every MaterialIcons code point that has a `_rounded` variant to that
variant's code point, so stored user icons draw in the rounded style with
nothing migrated. Rerun after a Flutter upgrade:
  python3 tool/icons/rounded_table.py ~/development/flutter-3.47.5
"""
import os
import re
import sys

sdk = sys.argv[1]
src = open(os.path.join(sdk, 'packages/flutter/lib/src/material/icons.dart')).read()
points = dict(re.findall(
    r"static const IconData (\w+) = IconData\((0x[0-9a-f]+), fontFamily: 'MaterialIcons'", src))
pairs = sorted({(int(points[n], 16), int(points[n + '_rounded'], 16))
                for n in points
                if not n.endswith(('_rounded', '_outlined', '_sharp')) and n + '_rounded' in points
                and points[n] != points[n + '_rounded']})
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
with open(os.path.join(root, 'lib/core/utils/material_icon_rounded.g.dart'), 'w') as f:
    f.write('// GENERATED by tool/icons/rounded_table.py from Flutter\'s icons.dart.\n')
    f.write('// Do not edit by hand.\n\n')
    f.write('/// MaterialIcons code point → its `_rounded` variant (ADR 0005).\n')
    f.write('const materialRounded = <int, int>{\n')
    for a, b in pairs:
        f.write(f'  0x{a:x}: 0x{b:x},\n')
    f.write('};\n')
print(len(pairs), 'pairs')
